### ISSUE TITLE
Implement Stats Tracker

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#117]
Backend requirements:
- Track and provide in the API:
  - How many times a user has bought cards (checked out from the Checkout) - "Purchases"
  - How many sales the user has done (orders). - "Sales"
  - Sales this month - "Sales This Month"
  - Average rating from reviews - "Seller Rating"
  - How many times has the seller rejected a sale. - "Rejection Rate"
  - How many times has the seller not sent a sale. - "Miss Rate"

Frontend requirements:
- Display the correct information in the User Profile section.

![image](https://github.com/julkascript/cardflow/assets/59143945/09356c8c-eca6-406b-8c52-a29a11097f06)

**Comment by milensski** [comment]
I have a question about the last point:

- > How many times has the seller not sent a sale. - "Miss Rate"

Currently, for an order status, we only save if it's rejected for whatever the reason is, both from the seller and buyer,
I can figure out a way to check how many times the seller rejected but I am not sure how to check with the current setup if he missed to sent, since there is only a status rejected.

**Comment by milensski** [comment]
Can you please check my logic and advise if you agree that we can count it like that,

- How many times has the seller rejected a sale. - "Rejection Rate" -> a rejection rate will be counted if the seller after status ordered immediately rejected the order.

- How many times has the seller not sent a sale. - "Miss Rate" -> miss rate will be counted if the seller sent the order but the buyer marked it as not received.

**Comment by julkascript** [comment]
- Yes
- No. There is the possibility that a seller can just literally not send a package (ghost the buyer). So if the seller does not send the package in 7 days, we should mark the order as "not sent".

**Comment by milensski** [comment]
I understand, that makes sense now. Thanks! 🙌
