### ISSUE TITLE
Trade Statuses are not accurate

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#175]
The Trade Statuses are currently messed up. We need to align them to the expected behavior:
1. Requesting a trade (== negotiating) auto-accepts for you, and "unaccepts" for the other person. Example: User A requests trade - user  B is pending for accept or decline. User B negotiates - now User A is pending.
2.  The checks in the "Current Offer" side menu need to be aligned with the state - who has accepted, who is pending, etc.
3. The status in the /trade page needs to also be accurate - whose turn it is for action.

**Comment by RyotaMitaraiWeb** [comment]
Seeking a clarification on something, just to ensure it's not a regression that was missed:

as of #179 (which addressed some of the concerns in this issue), a recipient cannot change the cash amount that the initiator should give and vice-versa (with the error message being pretty explicit about this). Is this supposed to be the actual behavior, though? I would think it's reasonable for someone to have the ability to request some cash if the other user does not have cards that interest them.

Question is relevant because:
1. The frontend currently sends a cash of 0 for the respective side if it's not specified. If the behavior above is correct, then a minor refactor is needed on the frontend so that it does not send cash properties at all when not needed.
2. If the behavior above is correct, I could look into hiding / disabling the field for the opposing side because it would be pointless in this case

(If the behavior isn't correct, I can fix it in my own PR, since it comes down to removing two conditional checks)

**Comment by julkascript** [comment]
Yes, we totally missed it, @dinocom33. The Recipient and the Initiator can both change the listings and cash. It's not dangerous, because:
- when initiator offers - the recipient needs to confirm
- when recipient negotiates - the initiator needs to confirm 
- etc.

**Comment by dinocom33** [comment]
@RyotaMitaraiWeb If you can fix it in your PR that's fine with me. If not, I'll make a new branch and release the PR.

**Comment by dinocom33** [comment]
@RyotaMitaraiWeb If you can fix it in your PR that's fine with me. If not, I'll make a new branch and release the PR.

**Comment by RyotaMitaraiWeb** [comment]
Leave it to me
