### ISSUE TITLE
Docker not reacting to changes in the code

### ISSUE THREAD

**Issue by julkascript** [julkascript/cardflow#21]
Have a code change and observe how the Docker server is not picking up the change.

**Comment by dinocom33** [comment]
To make Docker responsive to code changes, we added the following line to the docker-compose.yml file:
```
    volumes:
      - .:/usr/src/app
```
We also found that when the container is restarted, the base is completely cleared by the following command in entrypoint.sh file:
```
python manage.py flush --no-input
```
As we are not sure if this is a bug or by design, this command has only been commented out and not removed.
